services:
  # Container do Banco de Dados
  web:
    build:
      context: .
    image: host
    container_name: vaggo_web
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
#   db:
#     image: postgres:18-alpine
#     container_name: vaggo_postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: vaggo
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data # Salva os dados para não sumirem quando o container desligar

#   # Container da sua API Node.js
#   api:
#     build: .
#     container_name: vaggo_api
#     restart: always
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     environment:
#       - PORT=3000
#       - DB_HOST=db
#       - DB_USER=postgres
#       - DB_PASSWORD=12345
#       - DB_NAME=vaggo
#       - DB_PORT=5432
#       - JWT_SECRET=4f92b7c1d8e3a5b6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c
#     depends_on:
#       - db

# volumes:
#   pgdata:
